apiVersion: v1
kind: Namespace
metadata:
  name: tictactoe-system #Similar to kube-system
---
apiVesion: v1
kind: Deployment
metadata:
  name: tictactoe-pod
  namespace: tictactoe-system
spec:
  selector:
    matchLabels:
      app: tictactoe
    template:
      metadata:
        labels:
          app: tictactoe
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        terminationGracePeriodSeconds: 60
        containers:
        - name: tictactoe-app
          image: tictactoe-service:1.0

